### Login Request to Retrieve Auth Token
POST http://lb-49d70a12.elb.localhost.localstack.cloud :4004/auth/login
content-Type: application/json

{
  "email": "testuser@test.com",
  "password": "password123"
}

> {%
    console.log(response.body.token);
    client.global.set("token", response.body.token);
%}

